[project]
name = "f1-fantasy-client"
version = "0.1.0"
description = "A performant, typed API for the Formula 1 Fantasy game."
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.3",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
